# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format="""
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\

$character"""
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "blue"

[git_branch]
format='[$symbol$branch(:$remote_branch)]($style) '

[time]
disabled = false
format = '\[[$time]($style)\] '
